version: '3.8'

services:
  # 后端服务 - 使用MySQL数据库
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: infini-backend
    restart: unless-stopped
    ports:
      - "33201:3000"
    environment:
      - NODE_ENV=production
      - DB_TYPE=mysql
      - DB_HOST=infini-mysql
      - DB_PORT=3306
      - DISABLE_IP_CHECK=true  # 禁用IP检查，允许Docker网络内部通信
      # 其他环境变量将从.env文件中读取
    volumes:
      - ./backend/.env:/app/.env
    networks:
      - infini-network
    depends_on:
      - mysql

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: infini-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - infini-network

  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: infini-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=infini_manager
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backend/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - infini-network

# 定义网络，使服务之间可以通信
networks:
  infini-network:
    driver: bridge